services:
  api:
    build: .
    container_name: fastAPI
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
  db:
    image: mongo
    container_name: MongoDB
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: db_data
        target: /data/db
volumes:
  db_data: